# BUILD Stage
FROM golang:1.18-alpine as build
ENV CGO_ENABLED 1

RUN apk add git wget gcc g++

WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
ENTRYPOINT ["./tests/unit/run_tests.sh"]